<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveMarketExplorer.csproj" />
    <Reference Include="EveParser.Core">
      <HintPath>..\Libs\EveParser.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
